---
title: "Fantasy Football Project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
rb = read_csv("RB_season.csv")
rb %>% ggplot(aes(x = Rank, y = RushingTD)) + geom_point() + ggtitle("Rushing TD's vs Fantasy Rank of RB's") + geom_smooth(method='lm', se = FALSE)


teamRunBlockWinRate = read_csv("Team Run Block Win Rate.csv")

new = merge(rb, teamRunBlockWinRate, by = "Team")

new %>% filter(Rank.x <= 24) %>% ggplot(aes( x = `Win Rate (%)`, y = TotalPoints, label = PlayerName)) + geom_point() + geom_text(hjust=0, vjust=0) + ggtitle("Fantasy Points vs Run Block Win Rate of Offensive Line") + geom_smooth(method='lm', se = FALSE)
```


```{r}
adp = read_csv("adp.csv")
adp1 = adp %>% select(Player, Team, AVG) %>% rename(PlayerName = Player)

rbADP = left_join(rb, adp1, by = "PlayerName")

#Top 36 RB's based on total points 
top36 = rbADP %>% filter(Rank <= 36)
mean(top36$TotalPoints)
top36 = top36 %>% mutate(Difference = (top36$TotalPoints - 186.8406))

#Top 36 draft picks 
top36Picks = rbADP %>% filter(AVG <= 45.0)
mean(top36Picks$TotalPoints)
top36Picks = top36Picks %>% mutate(Difference = (top36Picks$TotalPoints - 155.854))

top36Picks %>% mutate(PlayerName = fct_reorder(PlayerName, desc(AVG))) %>% ggplot(aes(x = PlayerName, y = Difference)) + geom_bar(stat="identity") + coord_flip() + ggtitle("RB's performance relative to an average RB (points)")

```


```{r}
wr = read.csv("WR_season.csv")
top10wr = read.csv("top10WR.csv")
top10wrNew = top10wr %>% select(WEEK, PLAYER, FPTS)
top10wrNew %>% ggplot(aes(x = FPTS)) + geom_histogram(bins = 11) + facet_wrap(~PLAYER) + geom_vline(aes(xintercept=mean(FPTS)),color="blue", linetype="dashed", size=1) 
```


```{r}
qb = read_csv("QB_season.csv")
newQb = qb %>% filter(Rank <= 30) %>% mutate(Top15 = (Rank <= 15))

newQb %>% ggplot(aes(x = Top15, y = RushingYDS, fill = Top15)) + geom_boxplot() +coord_flip() + ggtitle('Rushing yards for Top 30 QBs (seperated by Top 15 and Bottom 15 QBs)')
```










